### ISSUE TITLE
I cannot download the dataset because i don't have permission to access /u/qyou/deepemotion/ on this server

### ISSUE THREAD

**Issue by DinghaoXi** [pohlinwei/AComPianist#1]
Could you please offer an alternative source of the data？

**Comment by pohlinwei** [comment]
I am sorry but I do not own the dataset, and thus I am unable to provide it. 😥 However, you could try (I have not tested it) looking at https://www.imageemotion.org

**Comment by MuizU** [comment]
@DinghaoXi were you able to get the dataset?

**Comment by MuizU** [comment]
@pohlinwei how were you able to get the dataset?
